{{ Html::script(asset('/assets/plugins/jquery/jquery.min.js')) }}
{{ Html::script(asset('/assets/plugins/bootstrap/js/popper.min.js')) }}
{{ Html::script(asset('/assets/plugins/bootstrap/js/bootstrap.min.js')) }}
{{ Html::script(asset('/assets/home/js/jquery.slimscroll.js')) }}
{{ Html::script(asset('/assets/home/js/waves.js')) }}
{{ Html::script(asset('/assets/home/js/sidebarmenu.js')) }}
{{ Html::script(asset('/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js')) }}
{{ Html::script(asset('/assets/plugins/sparkline/jquery.sparkline.min.js')) }}
{{ Html::script(asset('/assets/home/js/custom.min.js')) }}
{{ Html::script(asset('/assets/plugins/styleswitcher/jQuery.style.switcher.js')) }}
{{ Html::script(asset('/js/ajaxLogout.js')) }}
